version: 2
updates:
  # GitHub Actionsのバージョンを維持する
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Cargoの依存関係を維持する
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
