version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 1
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch:
        update-types:
          - "patch"
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nix:
        patterns:
          - "*"
