coverage:
  if: true
  paths:
    - lcov.info
testExecutionTime:
  if: true
  steps:
    - Test with coverage
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
