name: Rust CI
permissions:
  contents: read
on:
  push:
    branches: ["main"]
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Rust
        run: |
          rustup show
      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Check formatting
        run: cargo fmt --check
      - name: Run Clippy
        run: cargo clippy --no-deps --all-targets -- -D warnings
      - name: Build
        run: cargo build
      - name: Install dependencies for tests
        run: |
          sudo apt-get install -y --no-install-recommends zsh
      - name: Run tests
        run: cargo test
